### ISSUE TITLE
Rename HarmonyClient to Client

### ISSUE THREAD

**Issue by Slion** [Lakritzator/harmony#15]
Since it's already in the HarmonyHub namspace.

**Comment by Lakritzator** [comment]
I am against it, this doesn't read well:
var client = new Client(username, password);

The namespace is in the usings, not in the code.

**Comment by Slion** [comment]
Well in large projects you can't keep adding using directive all over the place.
If you do using HarmonyHub you are usually in small tiny project like HarmonyDemo and there it reads well because you are just in the HarmonyHub context.

In larger project you just don't add using directive and go for HarmonyHub.Client.

**Comment by Slion** [comment]
Also you either use namespace and don't use prefix or the other way around but not both.

**Comment by Slion** [comment]
Done.

**Comment by Lakritzator** [comment]
Horrible... I still don't know what it brings... typing 7 chars less, but not being able to see what is initiated.
